### ISSUE TITLE
Unable to Build Generated Plugin

### ISSUE THREAD

**Issue by johndanek** [videojs/generator-videojs-plugin#119]
Thanks for your help on #117 (I was able to get things running locally). I've since finished the plugin I built, but I am unable to use it as a module in my main project. If I try to run `npm install --only=dev` in the new module, I get the following error:

`
> sb-build

module.js:472
    throw err;
    ^

Error: Cannot find module './utils/commander-wrapper'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/myuser/dev/videojs-newplugin/node_modules/.bin/sb-build:2:24)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
`

I'm not surprised, as I can't find this `utils` folder it is trying to import CommanderWrapper from. 

When I add my new module to my main project's package.json:

    "devDependencies": {
        "videojs-newplugin": "file:../../../../videojs-newplugin"
    }

 and do an `npm install --only=dev` on the main project, I get the same error as before.

What must I do in order to build a new plugin and import it into an existing node app? Thanks!

**Comment by johndanek** [comment]
The issue was caused by copying the original folder to a new location which didn't include all hidden folders and files. Sorry!
