### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by johnsonjo4531** [videojs/generator-videojs-plugin#127]
I need to use both `window` and `document` in my plugin to make sure the videojs player is in view. I was running into problems running the test script in my plugin due to having `window` and `document` in my script.

Is there a best practice way to go about fixing this?

Here are my errors:

```
Unhandled rejection Error: No provider for "framework:detectBrowsers"! (Resolving: framework:detectBrowsers)
    at error (/Users/johnjohnson/Documents/projects/open-source/videojs-gifplayer/node_modules/di/lib/injector.js:22:12)
    at Object.get (/Users/johnjohnson/Documents/projects/open-source/videojs-gifplayer/node_modules/di/lib/injector.js:9:13)
    at Injector.get (/Users/johnjohnson/Documents/projects/open-source/videojs-gifplayer/node_modules/di/lib/injector.js:54:19)
    at /Users/johnjohnson/Documents/projects/open-source/videojs-gifplayer/node_modules/videojs-spellbook/node_modules/karma/lib/server.js:143:20
    at Array.forEach (native)
    at Server._start (/Users/johnjohnson/Documents/projects/open-source/videojs-gifplayer/node_modules/videojs-spellbook/node_modules/karma/lib/server.js:142:21)
    at Injector.invoke (/Users/johnjohnson/Documents/projects/open-source/videojs-gifplayer/node_modules/di/lib/injector.js:75:15)
    at Server.start (/Users/johnjohnson/Documents/projects/open-source/videojs-gifplayer/node_modules/videojs-spellbook/node_modules/karma/lib/server.js:103:18)
    at /Users/johnjohnson/Documents/projects/open-source/videojs-gifplayer/node_modules/videojs-spellbook/src/sb-test-browser:55:10
    at tryCatcher (/Users/johnjohnson/Documents/projects/open-source/videojs-gifplayer/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/johnjohnson/Documents/projects/open-source/videojs-gifplayer/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/johnjohnson/Documents/projects/open-source/videojs-gifplayer/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/johnjohnson/Documents/projects/open-source/videojs-gifplayer/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/johnjohnson/Documents/projects/open-source/videojs-gifplayer/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/johnjohnson/Documents/projects/open-source/videojs-gifplayer/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/johnjohnson/Documents/projects/open-source/videojs-gifplayer/node_modules/bluebird/js/release/async.js:143:10)
[test-browser       ][info ]: finished in 178ms
[test-node-all      ][info ]: start
[test-node-require  ][info ]: start
[test-node-require  ][fatal]: *******************************
[test-node-require  ][fatal]: node require failed with error:
[test-node-require  ][fatal]: build/es5/index.js:149
[test-node-require  ][fatal]: if (typeof document.hidden !== 'undefined') {
[test-node-require  ][fatal]:            ^
[test-node-require  ][fatal]: ReferenceError: document is not defined
[test-node-require  ][fatal]:     at Object.<anonymous> (build/es5/index.js:149:12)
[test-node-require  ][fatal]:     at Module._compile (module.js:570:32)
[test-node-require  ][fatal]:     at Object.Module._extensions..js (module.js:579:10)
[test-node-require  ][fatal]:     at Module.load (module.js:487:32)
[test-node-require  ][fatal]:     at tryModuleLoad (module.js:446:12)
[test-node-require  ][fatal]:     at Function.Module._load (module.js:438:3)
[test-node-require  ][fatal]:     at Module.require (module.js:497:17)
[test-node-require  ][fatal]:     at require (internal/module.js:20:19)
[test-node-require  ][fatal]:     at Object.<anonymous> (build/test/node-require.js:2:9)
[test-node-require  ][fatal]:     at Module._compile (module.js:570:32)
[test-node-require  ][fatal]: *******************************
[test-node-require  ][info ]: finished in 344ms
[test-node-all      ][fatal]: some commands failed!
[test-node-all      ][info ]: finished in 963ms
[test-all           ][fatal]: some commands failed!
[test-all           ][info ]: finished in 45506ms
[test               ][info ]: finished in 45754ms
```

**Comment by misteroneill** [comment]
@johnsonjo4531 For these globals, we add the npm `global` package as a dependency. You can then import them in your code like so:

```js
import document from 'global/document';
import window from 'global/window';
```

It looks like you're using the latest version of the generator, which includes our "spellbook" project, which is meant to be a kitchen sink builder/tool. Unfortunately, it's caused some hard-to-debug issues with a few projects. If you continue to experience problems, you might try installing v2 of the generator and using that instead:

```
npm i -g generator-videojs-plugin@latest-2
```

**Comment by misteroneill** [comment]
We are no longer using the Spellbook project. Please use a newer version of the generator and re-open if you continue seeing issues - thanks!
